version: '3.9'

services:
  mysql:
    image: mysql:latest
    command: |
      --default-authentication-plugin=mysql_native_password
      --default-storage-engine=InnoDB
      --character-set-server=utf8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weather_monitor
      MYSQL_USER: weather_monitor_user
      MYSQL_PASSWORD: password
    platform: linux/amd64

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
